STATUS_OPEN = 'open'
STATUS_PENDING = 'pending'
STATUS_CANCELED = 'canceled'
STATUS_EXPIRED = 'expired'
STATUS_FAILED = 'failed'
STATUS_PAID = 'paid'
STATUS_AUTHORIZED = 'authorized'

HOLD_STATUS = [STATUS_PAID, STATUS_OPEN, STATUS_PENDING, STATUS_AUTHORIZED]
