"""add_promoter_terms

Revision ID: 088dc6d7bb54
Revises: 2881ee57cd05
Create Date: 2020-07-14 20:34:56.418313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088dc6d7bb54'
down_revision = '2881ee57cd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('promoter_terms_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'configuration', 'file', ['promoter_terms_id'], ['file_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'configuration', type_='foreignkey')
    op.drop_column('configuration', 'promoter_terms_id')
    # ### end Alembic commands ###
