"""test_email

Revision ID: 204e127928ed
Revises: 974b6a980dd4
Create Date: 2019-12-16 21:18:21.535997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204e127928ed'
down_revision = '974b6a980dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('test_email', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration', 'test_email')
    # ### end Alembic commands ###
