"""add_invoice_configuration_options

Revision ID: 2877118c4f0b
Revises: 0d05d2d77bfa
Create Date: 2020-06-11 12:44:03.122553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2877118c4f0b'
down_revision = '0d05d2d77bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('invoice_email_address', sa.String(length=128), nullable=False))
    op.add_column('configuration', sa.Column('invoice_iban', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration', 'invoice_iban')
    op.drop_column('configuration', 'invoice_email_address')
    # ### end Alembic commands ###
