"""add_description_to_party

Revision ID: 30aba17e2805
Revises: 7d1507cd3d63
Create Date: 2020-05-07 22:49:19.865816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30aba17e2805'
down_revision = '7d1507cd3d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('description', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party', 'description')
    # ### end Alembic commands ###
