"""add_receipt_path_to_refund

Revision ID: 37db5cfa2f88
Revises: 088dc6d7bb54
Create Date: 2020-07-15 14:13:27.320674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37db5cfa2f88'
down_revision = '088dc6d7bb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund', sa.Column('receipt_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund', 'receipt_path')
    # ### end Alembic commands ###
