"""add_document_paths_to_purchase

Revision ID: 4d9112a4683e
Revises: 39f71f406904
Create Date: 2020-06-03 15:47:30.485949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9112a4683e'
down_revision = '39f71f406904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('invoice_path', sa.String(length=512), nullable=True))
    op.add_column('purchase', sa.Column('tickets_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'tickets_path')
    op.drop_column('purchase', 'invoice_path')
    # ### end Alembic commands ###
