"""add_country_to_user

Revision ID: 58668b58765e
Revises: 24458728adf1
Create Date: 2020-06-15 21:03:10.792841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58668b58765e'
down_revision = '24458728adf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
