"""files

Revision ID: 625b05fa277a
Revises: ec38b22c3a6d
Create Date: 2019-09-08 18:29:37.426368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625b05fa277a'
down_revision = 'ec38b22c3a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party.party_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('party_files',
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.file_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['party.party_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.UniqueConstraint('party_id', 'file_id', name='_party_file_uc')
    )
    op.add_column('configuration', sa.Column('allowed_image_types', sa.String(length=256), server_default='jpg,jpeg,png', nullable=False))
    op.add_column('configuration', sa.Column('default_club_owner_commission', sa.Integer(), nullable=False))
    op.add_column('configuration', sa.Column('default_promoter_commission', sa.Integer(), nullable=False))
    op.add_column('configuration', sa.Column('site_available', sa.Boolean(), nullable=False))
    op.add_column('party', sa.Column('club_owner_commission', sa.Integer(), nullable=False))
    op.add_column('party', sa.Column('club_owner_id', sa.Integer(), nullable=True))
    op.add_column('party', sa.Column('image', sa.String(length=256), nullable=False))
    op.add_column('party', sa.Column('logo', sa.String(length=256), nullable=False))
    op.create_foreign_key('_party_user_link', 'party', 'users', ['club_owner_id'], ['user_id'])
    op.add_column('purchase', sa.Column('club_owner_commission', sa.Integer(), nullable=False))
    op.add_column('purchase', sa.Column('promoter_commission', sa.Integer(), nullable=False))
    op.add_column('purchase', sa.Column('promoter_id', sa.Integer(), nullable=True))
    op.create_foreign_key('_purchase_promoter', 'purchase', 'users', ['promoter_id'], ['user_id'])
    op.add_column('ticket', sa.Column('denied_entry', sa.Boolean(), nullable=False))
    op.add_column('ticket', sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('ticket', sa.Column('refunded', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_ticket_denied_entry'), 'ticket', ['denied_entry'], unique=False)
    op.add_column('users', sa.Column('activation_code', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('commission', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('hostess_id', sa.Integer(), nullable=True))
    op.create_foreign_key('_hostess_club_owner_link', 'users', 'users', ['hostess_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_hostess_club_owner_link', 'users', type_='foreignkey')
    op.drop_column('users', 'hostess_id')
    op.drop_column('users', 'commission')
    op.drop_column('users', 'activation_code')
    op.drop_index(op.f('ix_ticket_denied_entry'), table_name='ticket')
    op.drop_column('ticket', 'refunded')
    op.drop_column('ticket', 'number')
    op.drop_column('ticket', 'denied_entry')
    op.drop_constraint('_purchase_promoter', 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'promoter_id')
    op.drop_column('purchase', 'promoter_commission')
    op.drop_column('purchase', 'club_owner_commission')
    op.drop_constraint('_party_user_link', 'party', type_='foreignkey')
    op.drop_column('party', 'logo')
    op.drop_column('party', 'image')
    op.drop_column('party', 'club_owner_id')
    op.drop_column('party', 'club_owner_commission')
    op.drop_column('configuration', 'site_available')
    op.drop_column('configuration', 'default_promoter_commission')
    op.drop_column('configuration', 'default_club_owner_commission')
    op.drop_column('configuration', 'allowed_image_types')
    op.drop_table('party_files')
    op.drop_table('file')
    # ### end Alembic commands ###
