"""init

Revision ID: 711bc211f5b1
Revises: 
Create Date: 2020-04-21 21:11:31.351364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711bc211f5b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('reset_index', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=128), nullable=True),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.Column('access', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_seen', sa.DateTime(), nullable=True),
        sa.Column('auth_code', sa.String(length=128), nullable=True),
        sa.Column('club', sa.String(length=256), nullable=True),
        sa.Column('first_name', sa.String(length=128), nullable=True),
        sa.Column('last_name', sa.String(length=128), nullable=True),
        sa.Column('club_owner_id', sa.Integer(), nullable=True),
        sa.Column('commission', sa.Integer(), nullable=False),
        sa.Column('working', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(('club_owner_id',), ['users.user_id'], ),
        sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_access'), 'users', ['access'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table(
        'location',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('location_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('street', sa.String(length=256), nullable=False),
        sa.Column('street_number', sa.String(length=12), nullable=False),
        sa.Column('street_number_addition', sa.String(length=12), nullable=True),
        sa.Column('postal_code', sa.Integer(), nullable=False),
        sa.Column('postal_code_letters', sa.String(length=2), nullable=False),
        sa.Column('city', sa.String(length=256), nullable=False),
        sa.Column('maps_url', sa.String(length=512), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(('user_id',), ['users.user_id'], ),
        sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table(
        'code',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('code_id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=8), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(('user_id',), ['users.user_id'], ),
        sa.PrimaryKeyConstraint('code_id')
    )
    op.create_table(
        'party',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('party_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('location_id', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('party_start_datetime', sa.DateTime(), nullable=True),
        sa.Column('party_end_datetime', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(length=128), nullable=False),
        sa.Column('num_available_tickets', sa.Integer(), nullable=False),
        sa.Column('ticket_price', sa.Integer(), nullable=False),
        sa.Column('club_owner_id', sa.Integer(), nullable=True),
        sa.Column('club_owner_commission', sa.Integer(), nullable=False),
        sa.Column('promoter_commission', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(('club_owner_id',), ['users.user_id'], ),
        sa.ForeignKeyConstraint(('location_id',), ['location.location_id'], ),
        sa.PrimaryKeyConstraint('party_id')
    )
    op.create_index(op.f('ix_party_is_active'), 'party', ['is_active'], unique=False)
    op.create_table(
        'file',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('file_id', sa.Integer(), nullable=False),
        sa.Column('path', sa.String(length=256), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('logo', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('party_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(('party_id',), ['party.party_id'], ),
        sa.ForeignKeyConstraint(('user_id',), ['users.user_id'], ),
        sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table(
        'party_files',
        sa.Column('party_id', sa.Integer(), nullable=False),
        sa.Column('file_id', sa.Integer(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(('file_id',), ['file.file_id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(('party_id',), ['party.party_id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('party_id', 'file_id'),
        sa.UniqueConstraint('party_id', 'file_id', name='_party_file_uc')
    )
    op.create_table(
        'purchase',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('purchase_id', sa.Integer(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=128), nullable=False),
        sa.Column('first_name', sa.String(length=128), nullable=False),
        sa.Column('last_name', sa.String(length=128), nullable=False),
        sa.Column('email', sa.String(length=128), nullable=False),
        sa.Column('hash', sa.String(length=160), nullable=False),
        sa.Column('mollie_payment_id', sa.String(length=128), nullable=False),
        sa.Column('purchase_datetime', sa.DateTime(), nullable=True),
        sa.Column('ticket_price', sa.Integer(), nullable=False),
        sa.Column('party_id', sa.Integer(), nullable=True),
        sa.Column('code_id', sa.Integer(), nullable=True),
        sa.Column('promoter_id', sa.Integer(), nullable=True),
        sa.Column('promoter_commission', sa.Integer(), nullable=False),
        sa.Column('club_owner_commission', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(('code_id',), ['code.code_id'], ),
        sa.ForeignKeyConstraint(('party_id',), ['party.party_id'], ),
        sa.ForeignKeyConstraint(('promoter_id',), ['users.user_id'], ),
        sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_index(op.f('ix_purchase_email'), 'purchase', ['email'], unique=False)
    op.create_table(
        'ticket',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=False),
        sa.Column('denied_entry', sa.Boolean(), nullable=False),
        sa.Column('number', sa.Integer(), nullable=False),
        sa.Column('refunded', sa.Boolean(), nullable=False),
        sa.Column('purchase_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(('purchase_id',), ['purchase.purchase_id'], ),
        sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_ticket_denied_entry'), 'ticket', ['denied_entry'], unique=False)
    op.create_index(op.f('ix_ticket_used'), 'ticket', ['used'], unique=False)
    op.create_table(
        'refund',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('refund_id', sa.Integer(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('refund_datetime', sa.DateTime(), nullable=True),
        sa.Column('purchase_id', sa.Integer(), nullable=True),
        sa.Column('mollie_refund_id', sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(('purchase_id',), ['purchase.purchase_id'], ),
        sa.PrimaryKeyConstraint('refund_id')
    )
    op.create_table(
        'configuration',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('lock_id', sa.Integer(), nullable=False),
        sa.Column('mollie_api_key', sa.String(length=128), nullable=True),
        sa.Column('allowed_image_types', sa.String(length=256), server_default='jpg,jpeg,png', nullable=False),
        sa.Column('default_club_owner_commission', sa.Integer(), nullable=False),
        sa.Column('default_promoter_commission', sa.Integer(), nullable=False),
        sa.Column('site_available', sa.Boolean(), nullable=False),
        sa.Column('test_email', sa.String(length=128), nullable=True),
        sa.Column('terms_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(('terms_id',), ['file.file_id'], ),
        sa.PrimaryKeyConstraint('lock_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration')
    op.drop_table('refund')
    op.drop_index(op.f('ix_ticket_used'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_denied_entry'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_purchase_email'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_table('party_files')
    op.drop_table('file')
    op.drop_index(op.f('ix_party_is_active'), table_name='party')
    op.drop_table('party')
    op.drop_table('code')
    op.drop_table('location')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_access'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
