"""add_city_to_receipt

Revision ID: 7a9fdeb70868
Revises: c66ebf5dee7f
Create Date: 2020-07-14 14:31:48.389528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9fdeb70868'
down_revision = 'c66ebf5dee7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('receipt_city', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration', 'receipt_city')
    # ### end Alembic commands ###
