"""administration_costs_and_minimum_promoter_fee

Revision ID: 7d1507cd3d63
Revises: 44e0c349a1a1
Create Date: 2020-04-27 09:27:48.008071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1507cd3d63'
down_revision = '44e0c349a1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('administration_costs', sa.Integer(), nullable=False))
    op.add_column('configuration', sa.Column('minimum_promoter_commission', sa.Integer(), nullable=False))
    op.add_column('purchase', sa.Column('administration_costs', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('minimum_promoter_commission', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'minimum_promoter_commission')
    op.drop_column('purchase', 'administration_costs')
    op.drop_column('configuration', 'minimum_promoter_commission')
    op.drop_column('configuration', 'administration_costs')
    # ### end Alembic commands ###
