"""add_languages_and_terms_to_user

Revision ID: 8bc6815a8e53
Revises: 94373df809b1
Create Date: 2020-06-26 17:12:35.813623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc6815a8e53'
down_revision = '94373df809b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accepted_terms', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('invoice_language', sa.String(length=16), nullable=False))
    op.add_column('users', sa.Column('language', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_column('users', 'invoice_language')
    op.drop_column('users', 'accepted_terms')
    # ### end Alembic commands ###
