"""add_refund_number_to_refund

Revision ID: ae63950cf29d
Revises: 37db5cfa2f88
Create Date: 2020-07-15 14:49:38.493909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae63950cf29d'
down_revision = '37db5cfa2f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund', sa.Column('refund_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund', 'refund_number')
    # ### end Alembic commands ###
