"""add_invoice_data_to_user_and_config

Revision ID: c0f7c2e16338
Revises: aeb811c4cf2c
Create Date: 2020-06-08 22:59:28.438797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f7c2e16338'
down_revision = 'aeb811c4cf2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('invoice_city', sa.String(length=256), nullable=False))
    op.add_column('configuration', sa.Column('invoice_kvk_number', sa.String(length=128), nullable=True))
    op.add_column('configuration', sa.Column('invoice_legal_name', sa.String(length=128), nullable=True))
    op.add_column('configuration', sa.Column('invoice_postal_code', sa.Integer(), nullable=False))
    op.add_column('configuration', sa.Column('invoice_postal_code_letters', sa.String(length=2), nullable=False))
    op.add_column('configuration', sa.Column('invoice_street', sa.String(length=256), nullable=False))
    op.add_column('configuration', sa.Column('invoice_street_number', sa.String(length=12), nullable=False))
    op.add_column('configuration', sa.Column('invoice_street_number_addition', sa.String(length=12), nullable=True))
    op.add_column('configuration', sa.Column('invoice_vat', sa.Integer(), nullable=False))
    op.add_column('configuration', sa.Column('invoice_vat_number', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('business_entity', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('city', sa.String(length=256), nullable=False))
    op.add_column('users', sa.Column('invoice_kvk_number', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('invoice_legal_name', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('invoice_vat_number', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('postal_code_letters', sa.String(length=2), nullable=False))
    op.add_column('users', sa.Column('street', sa.String(length=256), nullable=False))
    op.add_column('users', sa.Column('street_number', sa.String(length=12), nullable=False))
    op.add_column('users', sa.Column('street_number_addition', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'street_number_addition')
    op.drop_column('users', 'street_number')
    op.drop_column('users', 'street')
    op.drop_column('users', 'postal_code_letters')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'invoice_vat_number')
    op.drop_column('users', 'invoice_legal_name')
    op.drop_column('users', 'invoice_kvk_number')
    op.drop_column('users', 'city')
    op.drop_column('users', 'business_entity')
    op.drop_column('configuration', 'invoice_vat_number')
    op.drop_column('configuration', 'invoice_vat')
    op.drop_column('configuration', 'invoice_street_number_addition')
    op.drop_column('configuration', 'invoice_street_number')
    op.drop_column('configuration', 'invoice_street')
    op.drop_column('configuration', 'invoice_postal_code_letters')
    op.drop_column('configuration', 'invoice_postal_code')
    op.drop_column('configuration', 'invoice_legal_name')
    op.drop_column('configuration', 'invoice_kvk_number')
    op.drop_column('configuration', 'invoice_city')
    # ### end Alembic commands ###
