"""change_user_address_columns_to_nullable

Revision ID: c6c7509bb1f8
Revises: 8bc6815a8e53
Create Date: 2020-06-27 15:27:09.948325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6c7509bb1f8'
down_revision = '8bc6815a8e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'city',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=True)
    op.alter_column('users', 'country',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=True)
    op.alter_column('users', 'postal_code',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users', 'postal_code_letters',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2),
               nullable=True)
    op.alter_column('users', 'street',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=True)
    op.alter_column('users', 'street_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'street_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12),
               nullable=False)
    op.alter_column('users', 'street',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=False)
    op.alter_column('users', 'postal_code_letters',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2),
               nullable=False)
    op.alter_column('users', 'postal_code',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=False)
    op.alter_column('users', 'country',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=False)
    op.alter_column('users', 'city',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=False)
    # ### end Alembic commands ###
