"""add_minimum_promoter_commission_to_purchase

Revision ID: cf75235c7223
Revises: 4d9112a4683e
Create Date: 2020-06-05 15:40:48.510288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf75235c7223'
down_revision = '4d9112a4683e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('minimum_promoter_commission', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'minimum_promoter_commission')
    # ### end Alembic commands ###
