"""add_refund_to_ticket

Revision ID: d39228b25e1d
Revises: ae63950cf29d
Create Date: 2020-07-20 18:45:30.624566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39228b25e1d'
down_revision = 'ae63950cf29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('refund_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket', 'refund', ['refund_id'], ['refund_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'refund_id')
    # ### end Alembic commands ###
