"""add_invoice_table

Revision ID: e7129d801c83
Revises: 2877118c4f0b
Create Date: 2020-06-11 14:40:53.835616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7129d801c83'
down_revision = '2877118c4f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('invoice_id', sa.Integer(), nullable=False),
        sa.Column('path', sa.String(length=256), nullable=True),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('serial_number', sa.Integer(), nullable=False),
        sa.Column('business_invoice', sa.Boolean(), nullable=False),
        sa.Column('language', sa.String(length=128), nullable=False),
        sa.Column('sent', sa.Boolean(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('cp_legal_name', sa.String(length=128), nullable=False),
        sa.Column('cp_street', sa.String(length=256), nullable=False),
        sa.Column('cp_street_number', sa.String(length=12), nullable=False),
        sa.Column('cp_street_number_addition', sa.String(length=12), nullable=True),
        sa.Column('cp_postal_code', sa.Integer(), nullable=False),
        sa.Column('cp_postal_code_letters', sa.String(length=2), nullable=False),
        sa.Column('cp_city', sa.String(length=256), nullable=False),
        sa.Column('cp_kvk_number', sa.String(length=128), nullable=False),
        sa.Column('cp_vat_number', sa.String(length=128), nullable=False),
        sa.Column('cp_iban', sa.String(length=128), nullable=False),
        sa.Column('cp_email_address', sa.String(length=128), nullable=False),
        sa.Column('invoice_legal_name', sa.String(length=128), nullable=False),
        sa.Column('invoice_street', sa.String(length=256), nullable=False),
        sa.Column('invoice_street_number', sa.String(length=12), nullable=False),
        sa.Column('invoice_street_number_addition', sa.String(length=12), nullable=True),
        sa.Column('invoice_postal_code', sa.Integer(), nullable=False),
        sa.Column('invoice_postal_code_letters', sa.String(length=2), nullable=False),
        sa.Column('invoice_city', sa.String(length=256), nullable=False),
        sa.Column('invoice_country', sa.String(length=256), nullable=True),
        sa.Column('invoice_kvk_number', sa.String(length=128), nullable=True),
        sa.Column('invoice_vat_number', sa.String(length=128), nullable=True),
        sa.Column('invoice_phone_number', sa.String(length=128), nullable=False),
        sa.Column('invoice_vat', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(('user_id',), ['users.user_id'], ),
        sa.PrimaryKeyConstraint('invoice_id')
    )
    op.add_column('party', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key('party_ibfk_4', 'party', 'invoice', ['invoice_id'], ['invoice_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('party_ibfk_4', 'party', type_='foreignkey')
    op.drop_column('party', 'invoice_id')
    op.drop_table('invoice')
    # ### end Alembic commands ###
