"""add_invoice_items_to_config

Revision ID: eb0ea221aefa
Revises: f9c94d39f24a
Create Date: 2020-06-03 10:52:43.817007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0ea221aefa'
down_revision = 'f9c94d39f24a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('invoice_address', sa.String(length=128), nullable=True))
    op.add_column('configuration', sa.Column('invoice_country', sa.String(length=128), nullable=True))
    op.add_column('configuration', sa.Column('invoice_phone', sa.String(length=128), nullable=True))
    op.add_column('configuration', sa.Column('invoice_title', sa.String(length=128), nullable=True))
    op.add_column('configuration', sa.Column('vat', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration', 'vat')
    op.drop_column('configuration', 'invoice_title')
    op.drop_column('configuration', 'invoice_phone')
    op.drop_column('configuration', 'invoice_country')
    op.drop_column('configuration', 'invoice_address')
    # ### end Alembic commands ###
