"""init

Revision ID: ec38b22c3a6d
Revises: 
Create Date: 2019-07-15 15:30:44.791994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec38b22c3a6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('lock_id', sa.Integer(), nullable=False),
    sa.Column('mollie_api_key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('lock_id')
    )
    op.create_table('party',
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('party_start_datetime', sa.DateTime(), nullable=True),
    sa.Column('party_end_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('num_available_tickets', sa.Integer(), nullable=False),
    sa.Column('ticket_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('party_id')
    )
    op.create_index(op.f('ix_party_is_active'), 'party', ['is_active'], unique=False)
    op.create_index(op.f('ix_party_status'), 'party', ['status'], unique=False)
    op.create_index(op.f('ix_party_title'), 'party', ['title'], unique=False)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reset_index', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('access', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_access'), 'users', ['access'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('code',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_table('purchase',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hash', sa.String(length=160), nullable=False),
    sa.Column('mollie_payment_id', sa.String(length=128), nullable=False),
    sa.Column('purchase_datetime', sa.DateTime(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['code.code_id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.party_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_index(op.f('ix_purchase_email'), 'purchase', ['email'], unique=False)
    op.create_table('refund',
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('refund_datetime', sa.DateTime(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('mollie_refund_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.purchase_id'], ),
    sa.PrimaryKeyConstraint('refund_id')
    )
    op.create_table('ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.purchase_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_ticket_used'), 'ticket', ['used'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_used'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_table('refund')
    op.drop_index(op.f('ix_purchase_email'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_table('code')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_access'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_party_title'), table_name='party')
    op.drop_index(op.f('ix_party_status'), table_name='party')
    op.drop_index(op.f('ix_party_is_active'), table_name='party')
    op.drop_table('party')
    op.drop_table('configuration')
    # ### end Alembic commands ###
