"""add_iban_to_invoice_table

Revision ID: ef56810ada80
Revises: e7129d801c83
Create Date: 2020-06-11 15:04:59.730473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef56810ada80'
down_revision = 'e7129d801c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('invoice_iban', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'invoice_iban')
    # ### end Alembic commands ###
