"""add_party_invoice_table

Revision ID: f01e57191aa1
Revises: 58668b58765e
Create Date: 2020-06-15 21:16:54.137318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f01e57191aa1'
down_revision = '58668b58765e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party_invoice',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('party_id', sa.Integer(), nullable=True),
        sa.Column('invoice_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(('invoice_id',), ['invoice.invoice_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(('party_id',), ['party.party_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('party_ibfk_4', 'party', type_='foreignkey')
    op.drop_column('party', 'invoice_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('invoice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('party_ibfk_4', 'party', 'invoice', ['invoice_id'], ['invoice_id'])
    op.drop_table('party_invoice')
    # ### end Alembic commands ###
