"""add_iban_to_user

Revision ID: f29de0067149
Revises: 30aba17e2805
Create Date: 2020-05-09 15:59:12.722277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29de0067149'
down_revision = '30aba17e2805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('iban', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('iban_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'iban_verified')
    op.drop_column('users', 'iban')
    # ### end Alembic commands ###
