"""add_interval_to_party

Revision ID: f9c94d39f24a
Revises: f29de0067149
Create Date: 2020-05-31 12:24:03.457926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c94d39f24a'
down_revision = 'f29de0067149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('interval', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party', 'interval')
    # ### end Alembic commands ###
