#!/bin/bash




clear
echo "Settings:"
echo "========="
echo "domain:"
echo $DOMAIN
echo "========="
echo "db password:"
echo $TEST_DB_PASSWORD
echo "secret key:"
echo $TEST_SECRET_KEY
echo "folder:"
echo $TEST_FOLDER
echo "email password:"
echo $TEST_EMAIL_PASSWORD
echo ""
echo "install TEST? (y/n)"
read continue
if [[ $continue = "y" ]]
then


echo "Create directory=============================="
cd
mkdir $TEST_FOLDER
cd $TEST_FOLDER
echo "Created directory============================="


echo "Installing git repository====================="
git clone https://github.com/AlenAlic/clubpromoters-api
cd clubpromoters-api
echo "Installing git repository complete============"


echo "Installing venv==============================="
python3 -m venv venv
source venv/bin/activate
pip install pip --upgrade
pip install setuptools --upgrade
pip install -r requirements.txt
pip install gunicorn
echo "Installing venv complete======================"


echo "Setting environment variables================="
bash -c  'cat > .env' << EOL
DEBUG = True
SECRET_KEY = $TEST_SECRET_KEY

DATABASE_URI = "mysql+pymysql://clubpromoters_test:$TEST_DB_PASSWORD@localhost:3306/clubpromoters_test?charset=utf8mb4"

MAIL_DEFAULT_SENDER = "no-reply@$DOMAIN"

PRETTY_URL = "test.$DOMAIN"
ALLOWED_URLS = ["https://test.$DOMAIN"]
EOL
echo "Setting environment variables done============"


echo "Create database and user======================"
sudo mysql<<EOF
CREATE DATABASE clubpromoters_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'clubpromoters_test'@'localhost' IDENTIFIED BY '$TEST_DB_PASSWORD';
GRANT ALL PRIVILEGES ON clubpromoters_test.* TO 'clubpromoters_test'@'localhost';
FLUSH PRIVILEGES;
EOF
echo "Created database and user====================="


echo "Migrating database============================"
flask db upgrade
deactivate
echo "Database migration complete==================="


echo "Setting up supervisor========================="
sudo bash -c 'cat > /etc/supervisor/conf.d/clubpromoters_test_api.conf' << EOL
[program:clubpromoters_test_api]
command=/home/$USER/$TEST_FOLDER/clubpromoters-api/venv/bin/gunicorn -b 127.0.0.1:4041 -w 2 run:app
directory=/home/$USER/$TEST_FOLDER/clubpromoters-api
user=$USER
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
EOL
sudo supervisorctl reload
echo "Setting up supervisor complete================"


echo "Setting up nginx=============================="
sudo -E bash -c 'cat > /etc/nginx/conf.d/test.api.$DOMAIN.conf' << EOL
server {
    listen 443 ssl http2;
    server_name test.api.$DOMAIN;

    location / {
        proxy_pass http://127.0.0.1:4041;
        proxy_redirect off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }

    access_log /var/log/test.api.$DOMAIN.access.log;
    error_log /var/log/test.api.$DOMAIN.error.log;

    ssl_certificate /etc/letsencrypt/live/api.$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.$DOMAIN/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;

}
server {
    server_name test.api.$DOMAIN;
    return 301 https://\$host\$request_uri;
}
EOL
sudo service nginx reload
echo "Setting up nginx complete====================="


echo "Creating update script========================"
bash -c 'cat > scripts/update' << EOL
cd clubpromoters-api

echo "Creating database backup===="
./cron/hourly
echo "========================Done"

echo "Checking out new version===="
git pull
echo "========================Done"

echo "Installing requirements====="
source venv/bin/activate
pip install -r requirements.txt
echo "========================Done"

echo "Migrating Database=========="
export FLASK_APP=run.py
flask db upgrade
deactivate
echo "========================Done"

echo "Restarting Services========="
sudo supervisorctl restart clubpromoters_test_api
sudo systemctl reload nginx
echo "========================Done"

cd ..
EOL
echo "Created update script========================="


echo "Creating backup folder========================"
mkdir backups
cd backups
mkdir weekly
cd ..
echo "Created backup folder========================="


echo "Creating cronjob files========================"
mkdir cron
cd cron
bash -c 'cat > weekly' << EOL
#! /bin/bash

cd
mysqldump --login-path=clubpromoters_test clubpromoters_test | xz -z > "$TEST_FOLDER/clubpromoters-api/backups/weekly/backup-\$(date +%Y%m%d-%H%M).db.xz";
EOL
sudo chmod 774 weekly
cd ..
echo "Created cronjob files========================="




else
echo "Skipping TEST installation."
fi
cd