
TABLE_USERS = "users"
TABLE_LOCATION = "location"
TABLE_CONFIGURATION = "configuration"
TABLE_PARTY = "party"
TABLE_TICKET = "ticket"
TABLE_PURCHASE = "purchase"
TABLE_REFUND = "refund"
TABLE_CODE = "code"
TABLE_FILE = "file"
TABLE_PARTY_FILES = "party_files"
TABLE_INVOICE = "invoice"
TABLE_PARTY_INVOICE = "party_invoice"
